# syntax = edrevo/dockerfile-plus
# Build stage
INCLUDE+ Dockerfile-base

# Build jvm stage
FROM amazoncorretto:25-alpine3.22-jdk AS jvm
COPY --from=build /home/soft.gen/out/soft.generator.cpp/*.jar /soft.generator.cpp/
WORKDIR /soft.generator.cpp
RUN jdeps --print-module-deps --multi-release 25 --ignore-missing-deps --class-path '*' -recursive soft.generator.cpp-1.2.4.jar > java.modules \
 && jlink --strip-java-debug-attributes --add-modules jdk.zipfs,$(cat java.modules) --output /java-generator

# Build result stage
FROM alpine
COPY --from=build /home/soft.gen/out/soft.generator.cpp/*.jar /usr/share/soft.generator.cpp/
COPY --from=jvm /java-generator /usr/lib/jvm/java-generator

ENTRYPOINT ["/usr/lib/jvm/java-generator/bin/java","-jar","/usr/share/soft.generator.cpp/soft.generator.cpp-1.2.4.jar"]
